<a href="https://colab.research.google.com/github/souadkhailia/Olympic_history/blob/main/The_verage_height_per_individual_olympian_per_year.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
path ="/content/drive/MyDrive/data/athleteEventsNoPersonal.csv"
df = pd.read_csv(path)
df.head()

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,5,21.0,185.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
1,5,21.0,185.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
2,5,25.0,185.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
3,5,25.0,185.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
4,5,27.0,185.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
df

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,5,21.0,185.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
1,5,21.0,185.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
2,5,25.0,185.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
3,5,25.0,185.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
4,5,27.0,185.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40611,135567,28.0,183.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
40612,135570,27.0,176.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
40613,135570,27.0,176.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40614,135571,30.0,185.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
40615,135571,34.0,185.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
df.shape

(40616, 12)

In [ ]:
df.describe()

                  ID           Age        Height          Year
count   40616.000000  39143.000000  31615.000000  40616.000000
mean    68140.888738     25.619498    175.381117   1978.653240
std     38830.405762      6.494926     10.561791     29.850461
min         5.000000     11.000000    135.000000   1896.000000
25%     34661.750000     21.000000    168.000000   1960.000000
50%     68016.500000     25.000000    175.000000   1988.000000
75%    101475.000000     28.000000    183.000000   2004.000000
max    135571.000000     74.000000    221.000000   2016.000000

In [ ]:
# c. Which columns have missing values?
df.isnull().sum()

ID            0
Age        1473
Height     9001
Team          0
NOC           0
Games         0
Year          0
Season        0
City          0
Sport         0
Event         0
Medal     34699
dtype: int64

In [ ]:

df['Medal'].value_counts()

Gold      2009
Bronze    1994
Silver    1914
Name: Medal, dtype: int64

In [ ]:
# Check for dubplicated data
df.duplicated().sum()

207

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40616 entries, 0 to 40615
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      40616 non-null  int64
 1   Age     39143 non-null  float64
 2   Height  31615 non-null  float64
 3   Team    40616 non-null  object
 4   NOC     40616 non-null  object
 5   Games   40616 non-null  object
 6   Year    40616 non-null  int64
 7   Season  40616 non-null  object
 8   City    40616 non-null  object
 9   Sport   40616 non-null  object
 10  Event   40616 non-null  object
 11  Medal   5917 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 3.7+ MB

In [ ]:
df.describe()

                  ID           Age        Height          Year
count   40616.000000  39143.000000  31615.000000  40616.000000
mean    68140.888738     25.619498    175.381117   1978.653240
std     38830.405762      6.494926     10.561791     29.850461
min         5.000000     11.000000    135.000000   1896.000000
25%     34661.750000     21.000000    168.000000   1960.000000
50%     68016.500000     25.000000    175.000000   1988.000000
75%    101475.000000     28.000000    183.000000   2004.000000
max    135571.000000     74.000000    221.000000   2016.000000

In [ ]:
df.isnull().sum()

ID            0
Age        1473
Height     9001
Team          0
NOC           0
Games         0
Year          0
Season        0
City          0
Sport         0
Event         0
Medal     34699
dtype: int64

In [ ]:
 df.groupby('ID')['Height'].mean()

ID
5         185.0
6         188.0
12        172.0
30        189.0
36        194.0
          ...
135553    168.0
135558    200.0
135567    183.0
135570    176.0
135571    185.0
Name: Height, Length: 20336, dtype: float64

In [ ]:
df.columns.tolist()

['ID',
 'Age',
 'Height',
 'Team',
 'NOC',
 'Games',
 'Year',
 'Season',
 'City',
 'Sport',
 'Event',
 'Medal']

In [ ]:

df['Sport'].value_counts()

Athletics                    5550
Gymnastics                   3732
Swimming                     3481
Shooting                     1773
Fencing                      1642
Cycling                      1638
Rowing                       1615
Cross Country Skiing         1498
Alpine Skiing                1396
Wrestling                    1134
Sailing                      1009
Football                      998
Equestrianism                 967
Canoeing                      957
Speed Skating                 893
Boxing                        852
Hockey                        833
Ice Hockey                    823
Biathlon                      783
Basketball                    661
Weightlifting                 609
Water Polo                    602
Handball                      572
Judo                          545
Art Competitions              514
Volleyball                    513
Bobsleigh                     469
Tennis                        439
Diving                        409
Ski Jumping                   371
Figure Skating                364
Table Tennis                  347
Archery                       308
Modern Pentathlon             258
Badminton                     233
Nordic Combined               210
Luge                          195
Short Track Speed Skating     169
Freestyle Skiing              157
Synchronized Swimming         138
Baseball                      135
Snowboarding                  132
Rhythmic Gymnastics           102
Beach Volleyball               87
Softball                       76
Taekwondo                      73
Triathlon                      69
Rugby Sevens                   51
Curling                        48
Golf                           44
Skeleton                       35
Rugby                          27
Trampolining                   26
Tug-Of-War                     18
Polo                           14
Lacrosse                        9
Alpinism                        5
Cricket                         4
Military Ski Patrol             3
Motorboating                    1
Name: Sport, dtype: int64

In [ ]:

df['Team'].value_counts()

United States                   2530
Great Britain                   1784
France                          1766
Italy                           1607
Germany                         1462
                                ...
Ormsund Roklub-2                   1
Three Leaves                       1
La Salle Turnverein, Chicago       1
Chinese Taipei-2                   1
Digby                              1
Name: Team, Length: 646, dtype: int64

In [ ]:
# d. How many entries correspond to the city of London?
df[df['City'] == 'London']

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
36,54,NaN,NaN,Iran,IRI,1948 Summer,1948,Summer,London,Boxing,Boxing Men's Heavyweight,NaN
42,67,26.0,179.0,Russia,RUS,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Javelin Throw,NaN
66,155,34.0,185.0,Egypt,EGY,2012 Summer,2012,Summer,London,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
69,159,19.0,167.0,Egypt,EGY,2012 Summer,2012,Summer,London,Synchronized Swimming,Synchronized Swimming Women's Team,NaN
72,185,31.0,NaN,Egypt,EGY,1948 Summer,1948,Summer,London,Fencing,"Fencing Men's Foil, Individual",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40577,135489,22.0,182.0,Russia,RUS,2012 Summer,2012,Summer,London,Swimming,Swimming Women's 200 metres Backstroke,Silver
40578,135489,22.0,182.0,Russia,RUS,2012 Summer,2012,Summer,London,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN
40590,135517,22.0,NaN,Austria,AUT,1948 Summer,1948,Summer,London,Swimming,Swimming Men's 100 metres Backstroke,NaN
40595,135528,28.0,181.0,Germany,GER,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,NaN
40609,135558,32.0,200.0,Poland,POL,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,NaN

In [ ]:
len(df[df['City'] == 'London'])

3370

In [ ]:
# e. What age is the youngest athlete in our sample data?
df['Age'].min()

11.0

In [ ]:
# a. How many athletes who participated in the Sport "Tug-Of-War" were from Team "Sweden" in our sample dataset?

sweden_tug_of_war = df[(df['Sport'] == 'Tug-Of-War') & (df['Team'] == 'Sweden')]
sweden_tug_of_war

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
10023,34205,22.0,NaN,Sweden,SWE,1908 Summer,1908,Summer,London,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,NaN
12681,43105,23.0,NaN,Sweden,SWE,1906 Summer,1906,Summer,Athina,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Bronze
13015,44087,29.0,182.0,Sweden,SWE,1906 Summer,1906,Summer,Athina,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Bronze
16250,55169,23.0,NaN,Sweden,SWE,1908 Summer,1908,Summer,London,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,NaN
19048,64266,21.0,NaN,Sweden,SWE,1908 Summer,1908,Summer,London,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,NaN
20550,68647,26.0,190.0,Sweden,SWE,1906 Summer,1906,Summer,Athina,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Bronze

In [ ]:
len(sweden_tug_of_war)

6

In [ ]:
# b. How many Gold medals were awarded to athletes who were over 40 years old?
df['Medal'].value_counts()

Gold      2009
Bronze    1994
Silver    1914
Name: Medal, dtype: int64

In [ ]:
df[(df['Age'] > 40) & (df['Medal'] == 'Gold')]

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
740,2735,41.0,168.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Shooting,"Shooting Men's Rapid-Fire Pistol, 25 metres",Gold
1103,4029,46.0,NaN,Argentina,ARG,1936 Summer,1936,Summer,Berlin,Polo,Polo Men's Polo,Gold
1421,4993,41.0,180.0,Mosk II,NOR,1920 Summer,1920,Summer,Antwerpen,Sailing,Sailing Mixed 10 metres,Gold
3040,10769,49.0,180.0,White Lady,DEN,1964 Summer,1964,Summer,Tokyo,Sailing,Sailing Mixed Three Person Keelboat,Gold
3270,11617,44.0,NaN,Heroine,GBR,1908 Summer,1908,Summer,London,Sailing,Sailing Mixed 7 metres,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...
38916,130271,43.0,NaN,Heira II,NOR,1920 Summer,1920,Summer,Antwerpen,Sailing,Sailing Mixed 12 metres,Gold
38952,130381,42.0,167.0,United States,USA,1972 Summer,1972,Summer,Munich,Archery,Archery Women's Individual,Gold
39193,130936,56.0,NaN,United States,USA,1908 Summer,1908,Summer,London,Shooting,"Shooting Men's Running Target, Double Shot",Gold
39197,130936,60.0,NaN,United States,USA,1912 Summer,1912,Summer,Stockholm,Art Competitions,Art Competitions Mixed Sculpturing,Gold
39365,131533,58.0,NaN,Cincinnati Archers,USA,1904 Summer,1904,Summer,St. Louis,Archery,Archery Women's Team Round,Gold

In [ ]:
# 3. Determine the average height
# a. All rows are included.
df['Height'].mean()

175.3811165585956

In [ ]:
# b. All rows are included but grouped by Event.
df.groupby('Event')['Height'].mean()

Event
Alpine Skiing Men's Combined                      178.547170
Alpine Skiing Men's Downhill                      178.211679
Alpine Skiing Men's Giant Slalom                  176.739394
Alpine Skiing Men's Slalom                        176.482143
Alpine Skiing Men's Super G                       179.850575
                                                     ...
Wrestling Women's Flyweight, Freestyle            158.100000
Wrestling Women's Heavyweight, Freestyle          173.444444
Wrestling Women's Light-Heavyweight, Freestyle    170.000000
Wrestling Women's Lightweight, Freestyle          162.666667
Wrestling Women's Middleweight, Freestyle         164.533333
Name: Height, Length: 726, dtype: float64

In [ ]:
# cAverage height of all unique athletes (no duplicates based on ID)
# new dataframe that I called "one_per_athlete"
one_per_athlete = df.drop_duplicates(subset = 'ID', keep = 'first')
one_per_athlete

,ID,Age,Height,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,5,21.0,185.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
6,6,31.0,188.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
14,12,31.0,172.0,Finland,FIN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Singles,NaN
15,30,26.0,189.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Lightweight Double Sculls,Silver
17,36,21.0,194.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Swimming,Swimming Men's 100 metres Butterfly,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40604,135553,21.0,168.0,Soviet Union,URS,1952 Summer,1952,Summer,Helsinki,Athletics,Athletics Women's Shot Put,Gold
40609,135558,32.0,200.0,Poland,POL,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,NaN
40610,135567,24.0,183.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
40612,135570,27.0,176.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
40614,135571,30.0,185.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
one_per_athlete['Height'].mean()

176.31818479042698

In [ ]:
per_one=df.groupby('ID')['Height'].mean().reset_index()
per_one

           ID  Height
0           5   185.0
1           6   188.0
2          12   172.0
3          30   189.0
4          36   194.0
...       ...     ...
20331  135553   168.0
20332  135558   200.0
20333  135567   183.0
20334  135570   176.0
20335  135571   185.0

[20336 rows x 2 columns]

In [ ]:
per_one['Height'].mean()

176.31818479042698